spring:
  application:
    name: auth-service

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  cloud:
    discovery:
      enabled: false

eureka:
  client:
    enabled: false

security:
  jwt:
    private-key-base64: ${JWT_PRIVATE_KEY_BASE64}
    public-key-base64: ${JWT_PUBLIC_KEY_BASE64}
    access-token-expiration-minutes: 15
    refresh-token-expiration-days: 7
