spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v0/auth/**, /api/v0/token/**
          filters:
            - StripPrefix=1

server:
  port: 8095

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_ZONE}
    fetch-registry: true
    register-with-eureka: true

security:
  jwt:
    public-key-base64: ${JWT_PUBLIC_KEY_BASE64}