spring:
  application:
    name: api-gateway
  profiles:
    active: ${SPRING_ACTIVE_PROFILE:dev}
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true