spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v0/auth/**
            - Path=/api/v0/token/**
          filters:
            - StripPrefix=1

server:
  port: 8095

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

security:
  jwt:
    public-key-base64: ${JWT_PUBLIC_KEY_BASE64}