apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: calmify
  labels:
    app: api-gateway
    tier: backend
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8095
      targetPort: 8080
  type: ClusterIP
