apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: calmify
  labels:
    app: discovery-server
    tier: backend
spec:
  selector:
    app: discovery-server
  ports:
    - port: 8761
      targetPort: 8080
  type: ClusterIP
